"""
Pytest Runner Module
====================
Executes generated test cases using pytest.

Academic Concepts:
- Automated Test Execution
- Test Result Analysis
- Software Quality Assurance
"""

import os
import sys
import subprocess
import tempfile
import logging
import json
from datetime import datetime

logger = logging.getLogger(__name__)


class PytestRunner:
    """
    Executes generated tests using pytest.
    
    Features:
    - Dynamic test file creation
    - Pytest execution with result capture
    - Structured result parsing
    - Execution time tracking
    """
    
    def __init__(self, output_dir: str = "generated_tests"):
        self.output_dir = output_dir
        self.logger = logging.getLogger(self.__class__.__name__)
        os.makedirs(output_dir, exist_ok=True)
    
    def run_tests(self, test_code: str, source_code: str, test_filename: str = "test_generated.py") -> dict:
        """
        Execute generated test code.
        
        Args:
            test_code: Generated test code string
            source_code: Original source code being tested
            test_filename: Name for the test file
            
        Returns:
            dict with execution results
        """
        results = {
            "success": False,
            "total": 0,
            "passed": 0,
            "failed": 0,
            "errors": 0,
            "execution_time": 0.0,
            "output": "",
            "test_details": [],
            "timestamp": datetime.now().isoformat()
        }
        
        try:
            # Create temporary directory for execution
            with tempfile.TemporaryDirectory() as tmpdir:
                # Write source code
                source_file = os.path.join(tmpdir, "source_module.py")
                with open(source_file, 'w') as f:
                    f.write(source_code)
                
                # Build test file with imports
                full_test_code = self._build_test_file(test_code, source_code)
                test_file = os.path.join(tmpdir, test_filename)
                with open(test_file, 'w') as f:
                    f.write(full_test_code)
                
                # Also save to output directory
                output_test_file = os.path.join(self.output_dir, test_filename)
                with open(output_test_file, 'w') as f:
                    f.write(full_test_code)
                
                # Run pytest
                start_time = datetime.now()
                result = subprocess.run(
                    [sys.executable, "-m", "pytest", test_file, "-v", "--tb=short", "--no-header"],
                    capture_output=True,
                    text=True,
                    cwd=tmpdir,
                    timeout=60,
                    env={**os.environ, "PYTHONPATH": tmpdir}
                )
                end_time = datetime.now()
                
                results["execution_time"] = (end_time - start_time).total_seconds()
                results["output"] = result.stdout + result.stderr
                results["success"] = True
                
                # Parse results
                self._parse_output(result.stdout, results)
                
        except subprocess.TimeoutExpired:
            results["output"] = "Test execution timed out (60s limit)"
            results["errors"] = 1
        except Exception as e:
            results["output"] = f"Execution error: {str(e)}"
            self.logger.error(f"Test execution failed: {e}")
        
        return results
    
    def _build_test_file(self, test_code: str, source_code: str) -> str:
        """Build a complete test file with proper imports."""
        # Extract function names from source code
        import ast
        try:
            tree = ast.parse(source_code)
            func_names = [
                node.name for node in ast.walk(tree)
                if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
            ]
            class_names = [
                node.name for node in ast.walk(tree)
                if isinstance(node, ast.ClassDef)
            ]
        except SyntaxError:
            func_names = []
            class_names = []
        
        # Build import line
        all_names = func_names + class_names
        if all_names:
            import_line = f"from source_module import {', '.join(all_names)}"
        else:
            import_line = "import source_module"
        
        return f'''"""
Auto-Generated Test Cases
Generated by AI Test Generator
Timestamp: {datetime.now().isoformat()}
"""
import pytest
{import_line}


{test_code}
'''
    
    def _parse_output(self, output: str, results: dict):
        """Parse pytest output to extract test results."""
        lines = output.splitlines()
        
        for line in lines:
            line = line.strip()
            if "PASSED" in line:
                results["passed"] += 1
                results["test_details"].append({
                    "name": line.split("::")[1].split(" ")[0] if "::" in line else line,
                    "status": "PASSED"
                })
            elif "FAILED" in line:
                results["failed"] += 1
                results["test_details"].append({
                    "name": line.split("::")[1].split(" ")[0] if "::" in line else line,
                    "status": "FAILED"
                })
            elif "ERROR" in line:
                results["errors"] += 1
                results["test_details"].append({
                    "name": line,
                    "status": "ERROR"
                })
        
        results["total"] = results["passed"] + results["failed"] + results["errors"]
        
        # Try to parse summary line
        for line in lines:
            if "passed" in line or "failed" in line:
                import re
                nums = re.findall(r'(\d+)\s+(passed|failed|error)', line)
                for count, status in nums:
                    if status == "passed":
                        results["passed"] = max(results["passed"], int(count))
                    elif status == "failed":
                        results["failed"] = max(results["failed"], int(count))
                    elif status == "error":
                        results["errors"] = max(results["errors"], int(count))
                results["total"] = results["passed"] + results["failed"] + results["errors"]
